# -*- coding: utf-8 -*-
"""(241007007_SerapHerkiloglu_Odev .ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgcEvkxuLHyRhgagNpVMKbfUuDY0qAl9

# Autism screening data

**Veri Seti Hakkında;**

Bu veri seti, Dr. Fadi Fayez tarafından geliştirilen ASDTests (ASDTests.com) adlı mobil uygulama aracılığıyla toplanmıştır. Amacı, Otizm Spektrum Bozukluğu (OSB) özelliklerini erken dönemde taramak ve analiz etmektir. Veriler, etik onay sürecinden geçtikten sonra toplanmıştır ve hem araştırma hem de klinik çalışmalar için değerlidir.

Veri seti iki ayrı dosya içermektedir:

Yalnızca küçük çocuklar (toddlers) için olan set (Q-CHAT-10 anketi kullanılmıştır),

Tüm yaş gruplarını (küçük çocuklar, çocuklar, ergenler ve yetişkinler) içeren birleşik set (her yaş grubuna uygun kısa AQ-10 versiyonları kullanılmıştır).

Bu veri seti şu tür analizler için uygundur:

*   Tanımlayıcı (descriptive) istatistikler
*   Makine öğrenmesi ile tahminleme (sınıflandırma, regresyon)
*   Kümelenme (clustering) ve segmentasyon
*   Otizm belirtilerinin yaşa göre değişiminin incelenmesi

> Hedef, makine öğrenmesi tekniklerinin otizm belirtilerini ne kadar başarılı tespit edebileceğini araştırmaktır.

# 1. Kaggle API Token'ını Yükle
"""

from google.colab import files
files.upload()  # kaggle.json dosyası

# Dosyayı doğru dizine taşı
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Kaggle API paketini yükle
!pip install -q kaggle

# Veri setini indir (örnek: autism-screening-for-toddlers)
!kaggle datasets download -d fabdelja/autism-screening-for-toddlers

# Zip dosyasını aç
!unzip -o autism-screening-for-toddlers.zip

import pandas as pd

df = pd.read_csv("Toddler Autism dataset July 2018.csv")  # Dosya adı indirilen zip'e göre değişebilir.
df.head()

print("Veri setinin boyutu (satır, sütun):", df.shape)

"""# İçeriğinde Ne Var?
Bu veri setinde genellikle aşağıdaki dosyalar bulunur (zip içinde):

Toddler Autism dataset July 2018.csv

Description.txt veya benzeri açıklama dosyası

Veri, toddlers (yani 1.5–3 yaş arası çocuklar) için Q-CHAT-10 tarama anketine dayalıdır. Bazı sütunlar şunlar olabilir:

Sütun Adı ve	Açıklaması:


*   **A1 - A10	Q-CHAT-10** sorularına verilen yanıtlar
*   **age**	Yaş (ay olarak)
*   **sex** Cinsiyet
*   **ethnicity**	Etnik köken
*   **jaundice**	Sarılık geçirmiş mi?
*   **family_mem_with_ASD**	Ailede ASD var mı?
*   **who_completed_the_test**	Anketi kim doldurdu
*   **Class/ASD	Hedef değişken** (ASD: Evet/Hayır)

"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
import seaborn as sns
import matplotlib.pyplot as plt

# Veri setini yükle
df = pd.read_csv("Toddler Autism dataset July 2018.csv")
print("İlk 5 Satır:")
display(df.head())
print("Sütunlar ve Türleri:")
print(df.dtypes)

"""# 1. Orijinal ham veri ile deneysel çalışma (hold-out)"""

# Gereksiz sütunları çıkardık. (örneğin ID veya açıklama amaçlı sütunlar)
df = df.drop(columns=['Case_No', 'Who completed the test'], errors='ignore')

# Hedef değişkeni kontrol et
target_col = 'Class/ASD Traits ' if 'Class/ASD Traits ' in df.columns else 'Class/ASD'

# Categorical kolonları label encoding ile sayıya çevirdik.
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].astype(str).str.strip()  # boşluklardan arındırdık.
        df[col] = LabelEncoder().fit_transform(df[col])

# Eksik verileri kontrol ettik.
print("\nEksik Veri Durumu:")
print(df.isnull().sum())

# Özellik ve hedef ayrımı yaptık.
X = df.drop(columns=[target_col])
y = df[target_col]

# Gerekli modül: sklearn.model_selection içinden train_test_split fonksiyonu kullanılacak
# Veriyi eğitim ve test seti olarak ayır
# X: Bağımsız değişkenler (özellikler), y: Bağımlı değişken (sınıf etiketi)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y)
# Sonuç:
# - X_train, y_train: Modelin eğitileceği veri
# - X_test, y_test  : Modelin test edileceği, performansın ölçüleceği veri

print("Eğitim verisi (X_train) örnek sayısı:", X_train.shape[0])
print("Test verisi (X_test) örnek sayısı:", X_test.shape[0])
print("Eğitim etiketleri (y_train) örnek sayısı:", y_train.shape[0])
print("Test etiketleri (y_test) örnek sayısı:", y_test.shape[0])

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(),
    "Naive Bayes": GaussianNB(),
    "Support Vector Machine": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier()
}

results = []
confusion_matrices = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    cm = confusion_matrix(y_test, y_pred)
    confusion_matrices[name] = cm

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    specificity = cm[0, 0] / (cm[0, 0] + cm[0, 1])  # TN / (TN + FP)

    results.append({
        "Model": name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall (Sensitivity)": rec,
        "Specificity": specificity,
        "F1 Score": f1
    })

# Plot confusion matrices side by side
fig, axes = plt.subplots(1, len(models), figsize=(5 * len(models), 4))

for ax, (name, cm) in zip(axes, confusion_matrices.items()):
    sns.heatmap(cm, annot=True, fmt="d", cmap="Greens", cbar=False, ax=ax)
    ax.set_title(name)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# DataFrame oluştur ve F1 Score'a göre sırala
results_df = pd.DataFrame(results)
results_df_sorted = results_df.sort_values("F1 Score", ascending=False)

# Stil verilmiş tablo
fig, ax = plt.subplots(figsize=(12, 2.5))
ax.axis('off')
tbl = ax.table(cellText=results_df_sorted.values,
               colLabels=results_df_sorted.columns,
               cellLoc='center',
               loc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(10)
tbl.scale(1.2, 1.5)

plt.title("Model Performans Karşılaştırması (F1 Score'a göre sıralı)", fontsize=12, pad=10)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# En iyi modelin belirlenmesi
best_model_name = results_df.sort_values("F1 Score", ascending=False).iloc[0]["Model"]
best_model = models[best_model_name]

print(f"\nEn iyi model: {best_model_name}")

# İlk 5 örnek için predict_proba ve predict çıktıları
y_pred_probs = best_model.predict_proba(X_test)[:5]
y_preds = best_model.predict(X_test[:5])

# DataFrame'e dönüştürme
df_preds = pd.DataFrame(y_pred_probs, columns=["Class 0 Prob", "Class 1 Prob"])
df_preds["Predicted Class"] = y_preds

# Stil verilmiş tablo
fig, ax = plt.subplots(figsize=(8, 2.5))
ax.axis('off')
tbl = ax.table(cellText=df_preds.round(6).values,
               colLabels=df_preds.columns,
               cellLoc='center',
               loc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(10)
tbl.scale(1.2, 1.5)

plt.title("Predict Proba & Tahmin Edilen Sınıf (İlk 5 Örnek)", fontsize=12, pad=10)
plt.tight_layout()
plt.show()

"""# 2- Dengesizlik ile başa çıkma deneysel çalışması (hold-out)"""

# Sınıf dağılımı (etiketlerin sayısı ve oranları)
print("Sınıf Dağılımı (Etiket Sayısı):")
print(y.value_counts())

print("\nSınıf Dağılımı (Oranlar):")
print(y.value_counts(normalize=True))

print("Orijinal sınıf dağılımı:")
print(y.value_counts())

from sklearn.model_selection import train_test_split

# Orijinal tam veri setinden yeniden ayır
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from imblearn.over_sampling import SMOTE
from sklearn.metrics import (
    confusion_matrix, accuracy_score, precision_score,
    recall_score, f1_score, roc_auc_score
)
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# SMOTE ile veri dengeleme
smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

print("Oversampling sonrası sınıf dağılımı:")
print(pd.Series(y_train_sm).value_counts())

# Model sonuçlarını saklamak için liste
results_smote = []

# Model eğitimi ve değerlendirme
for name, model in models.items():
    model.fit(X_train_sm, y_train_sm)
    y_pred = model.predict(X_test)

    # predict_proba ya da decision_function kontrolü
    try:
        y_proba = model.predict_proba(X_test)[:, 1]
        auc = roc_auc_score(y_test, y_proba)
    except AttributeError:
        try:
            y_score = model.decision_function(X_test)
            auc = roc_auc_score(y_test, y_score)
        except:
            auc = None

    cm = confusion_matrix(y_test, y_pred)
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    spec = cm[0, 0] / (cm[0, 0] + cm[0, 1])

    results_smote.append({
        "Model": name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall (Sensitivity)": rec,
        "Specificity": spec,
        "F1 Score": f1,
        "ROC AUC": auc
    })

# Sonuçları DataFrame olarak hazırla ve sırala
results_smote_df = pd.DataFrame(results_smote)
results_smote_df = results_smote_df.sort_values("F1 Score", ascending=False)

# Stil verilmiş tablo çizimi
fig, ax = plt.subplots(figsize=(12, 1 + 0.25 * len(results_smote_df)))
ax.axis('off')
tbl = ax.table(cellText=results_smote_df.round(4).values,
               colLabels=results_smote_df.columns,
               cellLoc='center',
               loc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(10)
tbl.scale(1.2, 1.5)

plt.title("SMOTE Sonrası Modellerin Performansı", fontsize=12, fontweight='bold')
plt.show()

"""# 3- Normalizasyon deneysel çalışması (hold-out)"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# X ve y verilerini önceden tanımladığını varsayıyorum

num_cols = ['A1','A2','A3','A4','A5','A6','A7','A8','A9','A10', 'Age_Mons', 'Qchat-10-Score']

X_norm = X.copy()

scaler = StandardScaler()
X_norm[num_cols] = scaler.fit_transform(X_norm[num_cols])

X_train_norm, X_test_norm, y_train, y_test = train_test_split(
    X_norm, y, test_size=0.2, random_state=42, stratify=y
)

models = {
    'Logistic Regression': LogisticRegression(random_state=42, max_iter=1000),
    'Random Forest': RandomForestClassifier(random_state=42),
    'Naive Bayes': GaussianNB(),
    'SVM': SVC(random_state=42, probability=True),
    'KNN': KNeighborsClassifier()
}

results_norm = []

for name, model in models.items():
    model.fit(X_train_norm, y_train)
    y_pred = model.predict(X_test_norm)

    cm = confusion_matrix(y_test, y_pred)
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    specificity = cm[0,0] / (cm[0,0] + cm[0,1])

    results_norm.append({
        "Model": name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall (Sensitivity)": rec,
        "Specificity": specificity,
        "F1 Score": f1
    })

results_norm_df = pd.DataFrame(results_norm).sort_values("F1 Score", ascending=False)

def plot_table(df, title):
    fig, ax = plt.subplots(figsize=(12, 1*0.6 + 1))
    ax.axis('tight')
    ax.axis('off')
    table = ax.table(cellText=df.round(3).values,
                     colLabels=df.columns,
                     cellLoc='center',
                     loc='center')
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.auto_set_column_width(col=list(range(len(df.columns))))
    plt.title(title, fontsize=14, fontweight='bold')
    plt.show()

plot_table(results_norm_df, "Normalizasyon Sonrası Seçilen 5 Modelin Performansı")

"""# 4 K-Fold Çapraz Doğrulama (Hold-out yerine)"""

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score

# K-fold ayarı
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Skorları hesaplamak için özel fonksiyonlar
scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score),
    'recall': make_scorer(recall_score),
    'f1': make_scorer(f1_score)
}

results_cv = []

for name, model in models.items():
    # Pipeline: önce scaler sonra model
    from sklearn.pipeline import make_pipeline
    pipeline = make_pipeline(StandardScaler(), model)

    # Çapraz doğrulama skorları
    scores = {}
    for metric in scoring.keys():
        cv_score = cross_val_score(pipeline, X, y, cv=kf, scoring=scoring[metric])
        scores[metric] = cv_score.mean()

    results_cv.append({
        "Model": name,
        "Accuracy": scores['accuracy'],
        "Precision": scores['precision'],
        "Recall (Sensitivity)": scores['recall'],
        "F1 Score": scores['f1']
    })

results_cv_df = pd.DataFrame(results_cv)
print("K-Fold Çapraz Doğrulama Sonuçları:")
display(results_cv_df.sort_values("F1 Score", ascending=False))

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# Beş model
models = {
    'Logistic Regression': LogisticRegression(random_state=42, max_iter=1000),
    'Random Forest': RandomForestClassifier(random_state=42),
    'Naive Bayes': GaussianNB(),
    'SVM': SVC(random_state=42, probability=True),
    'KNN': KNeighborsClassifier()
}

# X ve y veri setin daha önce tanımlanmalı (örneğin: X, y = ...)

# Veri setini test için ayıralım (confusion matrix için)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# K-Fold ayarı
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    'accuracy': make_scorer(accuracy_score),
    'precision': make_scorer(precision_score),
    'recall': make_scorer(recall_score),
    'f1': make_scorer(f1_score)
}

results_cv = []

for name, model in models.items():
    pipeline = make_pipeline(StandardScaler(), model)

    # K-Fold çapraz doğrulama skorları
    scores = {}
    for metric in scoring.keys():
        cv_score = cross_val_score(pipeline, X, y, cv=kf, scoring=scoring[metric])
        scores[metric] = cv_score.mean()

    results_cv.append({
        "Model": name,
        "Accuracy": scores['accuracy'],
        "Precision": scores['precision'],
        "Recall (Sensitivity)": scores['recall'],
        "F1 Score": scores['f1']
    })

results_cv_df = pd.DataFrame(results_cv)

# Confusion Matrixleri yan yana çizmek için subplot oluşturuyoruz (1 satır, 5 sütun)
fig, axes = plt.subplots(1, 5, figsize=(20, 4))

for ax, (name, model) in zip(axes, models.items()):
    pipeline = make_pipeline(StandardScaler(), model)
    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Greens', cbar=False, ax=ax)
    ax.set_title(name)
    ax.set_xlabel('Tahmin')
    ax.set_ylabel('Gerçek')

plt.tight_layout()
plt.show()

# K-Fold çapraz doğrulama sonuç tablosunu gösterelim
fig, ax = plt.subplots(figsize=(10, 2))
ax.axis('tight')
ax.axis('off')

table = ax.table(cellText=results_cv_df.values,
                 colLabels=results_cv_df.columns,
                 cellLoc='center',
                 loc='center')

table.auto_set_font_size(False)
table.set_fontsize(10)
table.auto_set_column_width(col=list(range(len(results_cv_df.columns))))

plt.title("K-Fold Çapraz Doğrulama Sonuçları", fontsize=14, fontweight='bold')
plt.show()

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# Modelleri tanımlayalım
models = {
    'Logistic Regression': LogisticRegression(random_state=42, max_iter=1000),
    'Random Forest': RandomForestClassifier(random_state=42),
    'Naive Bayes': GaussianNB(),
    'SVM': SVC(random_state=42, probability=True),
    'KNN': KNeighborsClassifier()
}

# Önceki kodda X_train, X_test, y_train, y_test zaten tanımlı olmalı

for name, model in models.items():
    pipeline = make_pipeline(StandardScaler(), model)
    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    # SVM, Naive Bayes, Random Forest, KNN ve Logistic Regression predict_proba destekler
    # Ancak bazı modellerde (örneğin SVM'de) probability=True parametresi yoksa hata verir
    try:
        y_proba = pipeline.predict_proba(X_test)[:, 1]
    except AttributeError:
        y_proba = None  # predict_proba desteklenmiyor

    print(f"Model: {name}")
    print("Predict sonuçları:", y_pred[:10])
    if y_proba is not None:
        print("Predict_proba sonuçları (pozitif sınıf):", y_proba[:10])
    else:
        print("Predict_proba desteklenmiyor.")
    print("-" * 50)

from sklearn.metrics import (
    confusion_matrix, accuracy_score, precision_score,
    recall_score, f1_score, roc_auc_score
)
import pandas as pd
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from scipy.special import expit

results_list = []

for name, model in models.items():
    pipeline = make_pipeline(StandardScaler(), model)
    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    # pipeline içindeki model objesini bul
    model_step_name = list(pipeline.named_steps.keys())[-1]
    model_in_pipe = pipeline.named_steps[model_step_name]

    # predict_proba kontrolü
    if hasattr(model_in_pipe, "predict_proba"):
        y_proba = pipeline.predict_proba(X_test)[:, 1]
    elif hasattr(model_in_pipe, "decision_function"):
        decision_scores = pipeline.decision_function(X_test)
        y_proba = expit(decision_scores)
    else:
        # ROC AUC hesaplanamayabilir
        y_proba = y_pred

    cm = confusion_matrix(y_test, y_pred)
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    spec = cm[0, 0] / (cm[0, 0] + cm[0, 1])
    try:
        auc = roc_auc_score(y_test, y_proba)
    except:
        auc = None

    results_list.append({
        "Model": name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall (Sensitivity)": rec,
        "Specificity": spec,
        "F1 Score": f1,
        "ROC AUC": auc
    })

results_df = pd.DataFrame(results_list)
print("5 Modelin Performans Tablosu:")
display(results_df.sort_values("F1 Score", ascending=False))

from sklearn.metrics import (
    confusion_matrix, accuracy_score, precision_score,
    recall_score, f1_score, roc_auc_score
)
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from scipy.special import expit  # decision_function için sigmoid

model_results = []

for name, model in models.items():
    pipeline = make_pipeline(StandardScaler(), model)
    pipeline.fit(X_train_sm, y_train_sm)

    y_pred = pipeline.predict(X_test)

    # predict_proba kontrolü
    model_step_name = list(pipeline.named_steps.keys())[-1]
    model_in_pipe = pipeline.named_steps[model_step_name]

    if hasattr(model_in_pipe, "predict_proba"):
        y_proba = pipeline.predict_proba(X_test)[:, 1]
    elif hasattr(model_in_pipe, "decision_function"):
        decision_scores = pipeline.decision_function(X_test)
        y_proba = expit(decision_scores)  # sigmoid ile olasılığa çevir
    else:
        y_proba = y_pred  # AUC hesaplanamaz ama devam

    cm = confusion_matrix(y_test, y_pred)
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    spec = cm[0, 0] / (cm[0, 0] + cm[0, 1])
    try:
        auc = roc_auc_score(y_test, y_proba)
    except:
        auc = None

    model_results.append({
        "Model": name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall (Sensitivity)": rec,
        "Specificity": spec,
        "F1 Score": f1,
        "ROC AUC": auc
    })

results_df = pd.DataFrame(model_results).sort_values("F1 Score", ascending=False)

print("Tüm Modellerin Performans Karşılaştırması (SMOTE + Normalizasyon sonrası):")
display(results_df)

import matplotlib.pyplot as plt
import seaborn as sns

# En iyi 2 modeli seçelim (F1 Score'a göre sıralı varsayıyoruz)
top2 = results_df.head(2).copy()

# Metrikleri uzun formata çevirelim (bar plot için)
metrics = ["Accuracy", "Precision", "Recall (Sensitivity)", "Specificity", "F1 Score", "ROC AUC"]
top2_melted = top2.melt(id_vars=["Model"], value_vars=metrics,
                        var_name="Metric", value_name="Score")

plt.figure(figsize=(10,6))
sns.barplot(data=top2_melted, x="Metric", y="Score", hue="Model", palette="Greens")

plt.title("En İyi İki Model Performans Karşılaştırması (Yeşil Tonları)")
plt.ylim(0,1)  # Metrikler 0-1 arasında olduğundan
plt.xticks(rotation=45)
plt.legend(title="Model")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# En kötü 2 modeli seçelim (F1 Score'a göre sıralı)
worst2 = results_df.tail(2).copy()

# Metrikleri uzun formata çevirelim (bar plot için)
metrics = ["Accuracy", "Precision", "Recall (Sensitivity)", "Specificity", "F1 Score", "ROC AUC"]
worst2_melted = worst2.melt(id_vars=["Model"], value_vars=metrics,
                            var_name="Metric", value_name="Score")

plt.figure(figsize=(10,6))
sns.barplot(data=worst2_melted, x="Metric", y="Score", hue="Model", palette="Greens")

plt.title("En Kötü İki Model Performans Karşılaştırması")
plt.ylim(0,1)
plt.xticks(rotation=45)
plt.legend(title="Model")
plt.tight_layout()
plt.show()

# En iyi modeli F1 Score'a göre belirleyelim
best_row = results_df.sort_values("F1 Score", ascending=False).iloc[0]
best_model_name = best_row["Model"]
acc = best_row["Accuracy"]
prec = best_row["Precision"]
rec = best_row["Recall (Sensitivity)"]
spec = best_row["Specificity"]
f1 = best_row["F1 Score"]
auc = best_row["ROC AUC"]

# Açıklayıcı metni oluştur
summary_text = f"""
Bu çalışma kapsamında değerlendirilen beş farklı makine öğrenmesi modelinin performansları;
doğruluk (accuracy), kesinlik (precision), duyarlılık (recall), özgüllük (specificity),
F1 skoru ve ROC AUC gibi çeşitli sınıflandırma başarı ölçütleri kullanılarak karşılaştırılmıştır.
Uygulanan SMOTE yöntemi ve verilerin standartlaştırılması sonrasında elde edilen sonuçlara göre,
**{best_model_name}** modeli en iyi performansı göstermiştir.
Bu model, doğruluk: {acc:.3f}, kesinlik: {prec:.3f}, duyarlılık: {rec:.3f}, özgüllük: {spec:.3f},
F1 skoru: {f1:.3f} ve ROC AUC: {auc:.3f} değerleriyle hem pozitif sınıfı doğru tanılamadaki başarısı
(duyarlılık), hem de yanlış pozitif oranının düşüklüğü (özgüllük) açısından öne çıkmıştır.
Bu nedenle, analizlerde ve uygulamalarda bu modelin tercih edilmesi uygun görülmüştür.
"""

print(summary_text)